jwt:
  secret:
    access: LejjnLZua6SlR7eZXByD2+9M5P+dYxK3IlfA6XgPksuXijiXMAcpulI03o2Vq+PjYENhgTJGXLNm7YS4f1+IMw==
    refresh: cRO8f7Q/HaE/X1QjxAHYL8Dm5qkTI68WiNi9elE1NFqsL2up0RlZn/e7aD2R5i8cMvCksBEDhUAOZAhsypQaXw==
spring:
  application:
    name: Spring_Application
server:
  port: 9000
  logging:
    level:
      org: info
      com: off
---

spring:
  profiles:
    active: local

---
logging:
  level:
    root: info
    com.danIT.HW.Spring_Aplication: info

---
spring:
  config:
    activate:
      on-profile: local
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema-h2.sql
  datasource:
    url: jdbc:h2:mem:data
    username: root
    password:
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: false
    show-sql: true
  logging:
    level:
      org: info
      com: off

---

spring:
  config:
    activate:
      on-profile: prod
  flyway:
    enabled: false
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema-postgres.sql
  datasource:
    url: jdbc:postgresql://localhost:5432/data
    username: user
    password: dbdata
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: false
    show-sql: false
  logging:
    level:
      org: info
      com: off
